/*
Copyright Obaydullah.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/obaydullahmhs/crd-controller/pkg/apis/aadee.apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAadees implements AadeeInterface
type FakeAadees struct {
	Fake *FakeAadeeV1alpha1
	ns   string
}

var aadeesResource = schema.GroupVersionResource{Group: "aadee.apps", Version: "v1alpha1", Resource: "aadees"}

var aadeesKind = schema.GroupVersionKind{Group: "aadee.apps", Version: "v1alpha1", Kind: "Aadee"}

// Get takes name of the aadee, and returns the corresponding aadee object, and an error if there is any.
func (c *FakeAadees) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Aadee, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(aadeesResource, c.ns, name), &v1alpha1.Aadee{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Aadee), err
}

// List takes label and field selectors, and returns the list of Aadees that match those selectors.
func (c *FakeAadees) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AadeeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(aadeesResource, aadeesKind, c.ns, opts), &v1alpha1.AadeeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AadeeList{ListMeta: obj.(*v1alpha1.AadeeList).ListMeta}
	for _, item := range obj.(*v1alpha1.AadeeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aadees.
func (c *FakeAadees) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(aadeesResource, c.ns, opts))

}

// Create takes the representation of a aadee and creates it.  Returns the server's representation of the aadee, and an error, if there is any.
func (c *FakeAadees) Create(ctx context.Context, aadee *v1alpha1.Aadee, opts v1.CreateOptions) (result *v1alpha1.Aadee, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(aadeesResource, c.ns, aadee), &v1alpha1.Aadee{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Aadee), err
}

// Update takes the representation of a aadee and updates it. Returns the server's representation of the aadee, and an error, if there is any.
func (c *FakeAadees) Update(ctx context.Context, aadee *v1alpha1.Aadee, opts v1.UpdateOptions) (result *v1alpha1.Aadee, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(aadeesResource, c.ns, aadee), &v1alpha1.Aadee{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Aadee), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAadees) UpdateStatus(ctx context.Context, aadee *v1alpha1.Aadee, opts v1.UpdateOptions) (*v1alpha1.Aadee, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(aadeesResource, "status", c.ns, aadee), &v1alpha1.Aadee{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Aadee), err
}

// Delete takes name of the aadee and deletes it. Returns an error if one occurs.
func (c *FakeAadees) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(aadeesResource, c.ns, name, opts), &v1alpha1.Aadee{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAadees) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(aadeesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AadeeList{})
	return err
}

// Patch applies the patch and returns the patched aadee.
func (c *FakeAadees) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Aadee, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(aadeesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Aadee{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Aadee), err
}
